[tool.poetry]
name = "resume-parser"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "*"
flask = "^1.0"
flask_sqlalchemy = "^2.3"
flask-migrate = "^2.2"

[tool.poetry.dev-dependencies]
