"""empty message

Revision ID: 972b88e00104
Revises: 7bb3658e85a1
Create Date: 2018-09-25 15:22:20.838154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '972b88e00104'
down_revision = '7bb3658e85a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hacker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('resume', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hacker')
    # ### end Alembic commands ###
