"""empty message

Revision ID: a8b9d313cba1
Revises: 972b88e00104
Create Date: 2018-09-25 16:27:39.403407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8b9d313cba1'
down_revision = '972b88e00104'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hacker', sa.Column('filename', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hacker', 'filename')
    # ### end Alembic commands ###
